### ISSUE TITLE
Got "Property 'runAsync' does not exist on type '{}'" when calling command from EventHandler

### ISSUE THREAD

**Issue by mrik974** [vulcainjs/vulcain-corejs#25]
I'm trying to run this small piece of code : 
```
@Consume({ description: "Creates the user in directory when the user is created in user-service", subscribeToAction: "myMethod", filter: (events: rx.Observable<EventData>) => events.filter(e => e.status === "Success") })
    async onCreateCustomerAsync(person: User) {
        const cmd = await this.createCommandAsync("CreatePersonEntryCommand");
        const personEntry: PersonEntry = new PersonEntry();
        // Fill person entry
        let personEntryCreated = await cmd.runAsync<PersonEntry>(personEntry);
        return true;
    } 
```
When using `vulcain-corejs: 1.1.140` it works fine, but when I try to switch to the most recent version (`1.1.141`) i have the following error : `Property 'runAsync' does not exist on type '{}'`

Any idea?

**Comment by malain** [comment]
You must create an interface for your command and use it like this:
interface IPersonCommand {
    runAsync(person: PersonEntry): boolean;
}
    const cmd = await this.createCommandAsync<IPersonCommand>("CreatePersonEntryCommand");
    let personEntryCreated = await cmd.runAsync(personEntry);

**Comment by mrik974** [comment]
Here's the full code of my `Command`
```
@Command({executionTimeoutInMilliseconds: 1500})
class CreatePersonEntryCommand extends AbstractHttpCommand {

    constructor(@Inject(DefaultServiceNames.Container) container: IContainer) {
        super(container);
        // Create a custom service dynamic property
    }


    // Execute command
    async runAsync(param1: PersonEntry): Promise<PersonEntry> {
        // irrelevant code here
        return param1;
    }

}
```

**Comment by mrik974** [comment]
Here's the full code of my `Command`

```
@Command({executionTimeoutInMilliseconds: 1500})
class CreatePersonEntryCommand extends AbstractHttpCommand {

    constructor(@Inject(DefaultServiceNames.Container) container: IContainer) {
        super(container);
        // Create a custom service dynamic property
    }


    // Execute command
    async runAsync(param1: PersonEntry): Promise<PersonEntry> {
        // irrelevant code here
        return param1;
    }

}
```

I added the `Interface` but I still get the same Typescript transpilation error.
I've run tests on my code, and again, it works with version `1.1.140`

Either I'm still missing something or there's a bug, but there's definitely something I don't understand here.

**Comment by aguerot** [comment]
Your command should implement 
```ICreatePErsonEntryCommand```

**Comment by malain** [comment]
Sorry there is a mistake in the previous sample.
You must use this code instead.
```js
const cmd = await this.createCommandAsync<ICreatePersonEntryCommand>("CreatePersonEntryCommand");
let personEntryCreated = await cmd.runAsync(personEntry);
```

**Comment by mrik974** [comment]
It works. Thank you
